powp_lab
iis-powp-2018z/powp_plotter_project pull request #19
Opened 2018-11-22 22:16 UTC by 90rl

Please find below

2018-12-03 13:15 UTC, kowallus requested changes
LAB3: 4 pts
Specific remarks are inlined in the code.

LAB4: Required updates are marked using 'PLEASE FIX:' prefix.

2018-12-03 13:15 UTC, kowallus commented on .classpath
> +<classpath>
Commits polluted with project/compilation files (.settings, bin etc.).

2018-12-03 13:15 UTC, kowallus commented on src/main/java/edu/iis/powp/adapter/LinePlotterAdapter.java
> +		ILine line = LineFactory.getBasicLine();
Hardcoded line type. What about 3.3.2. test?

2018-12-03 13:15 UTC, kowallus commented on src/main/java/edu/iis/powp/command/FactoryCircle.java
> +    public ComplexCommand draw() {
The name is confusing. It is generation rather than drawing (call to execute draws)

2018-12-03 13:15 UTC, kowallus commented on src/main/java/edu/iis/powp/command/FactoryCircle.java
> +        	for(double x=MIN_X;x<MAX_X;x++ ) {
Code formatting is ugly.

2018-12-03 13:15 UTC, kowallus commented on src/test/java/edu/iis/powp/gui/TestPlotSoftPatterns.java
> +		IPlotter plotter3 = (IPlotter) new CommandDrawLineToPosition( DrawerFeature.getDrawerController());
This is obviously incorrect!!! Commands are not drivers.
PLEASE FIX: The test should be added to TESTS menu (addTest). It should generate and then execute a command.

2018-12-03 20:33 UTC, 90rl commented
Project correction

2018-12-05 14:30 UTC, kowallus requested changes
Required updates are marked using 'PLEASE FIX:' prefix.

2018-12-05 14:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/ComplexCommand.java
> +	private CommandDrawLineToPosition commandDrawLineToPosition;
I do not understand the purpose of attributes commandDrawLineToPosition and commandSetPosition. (Maybe you can remove them?)

2018-12-05 14:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/ComplexCommand.java
> +	public ComplexCommand() {
PLEASE FIX: The constructor should initialize plotterCommands attribute or there will be NullPointerExceptions!

2018-12-05 14:30 UTC, kowallus commented on src/main/java/edu/iis/powp/events/predefine/SelectTestCircleOptionListener.java
> +        FactoryCircle.draw();
PLEASE FIX: It does not work! Command is not executed on a driver (see FigureJoe tests)

2018-12-05 14:30 UTC, kowallus commented on src/main/java/edu/iis/powp/command/FactoryRectangle.java
> +    public static ComplexCommand draw() {
The name is STILL incorrect.

2018-12-07 12:08 UTC, kowallus commented
4.5 pts

Final laboratory grade: 4

2018-12-07 12:08 UTC, closed without merging