lab3
iis-powp-2018z/powp_plotter_project pull request #21
Opened 2018-12-03 11:14 UTC by kamilasyp

2018-12-03 12:19 UTC, kamilasyp commented
lab 3 + lab 4

2018-12-05 14:22 UTC, kowallus commented
Prośba o poprawki dotyczyła pani poprzedniego PR-a.
https://github.com/iis-powp-2018z/powp_plotter_project/pull/4
Miała Pani wprowadzić poprawki w ramach poprzedniego PR-a a nie usuwać repozytorium i wrzucić gotowę rozwiązanie "na czysto". Czy ma pani jeszcze kopię (lokalną) poprzedniego repozytorium? (tak żeby można było pracować na właściwej wersji)

2018-12-19 11:39 UTC, kowallus requested changes
Please fix all these minor issues.

2018-12-19 11:39 UTC, kowallus commented on src/main/java/edu/iis/powp/events/predefine/Rectangle.java
> +	public ComplexCommand getRectangleDrawCommand(int x, int y, int x2, int y2)
Names of parameters x2, y2 do not explain their true meaning!

2018-12-19 11:39 UTC, kowallus commented on src/main/java/edu/iis/powp/events/predefine/SelectTestFigureOptionListener.java
> +	    		PlotterCommand rectangleCommand = rectangleFactory.getRectangleDrawCommand(0, 0, 100, 50);
Using coordinates (0,0) is weak for testing purposes.

2018-12-19 11:39 UTC, kowallus commented on src/main/java/edu/iis/powp/events/predefine/SelectTestFigureOptionListener.java
> +	    		PlotterCommand traingleCommand = triangleFactory.getTriangleDrawCommand(0, 0, 50, 100, 150, 50);
Using coordinates (0,0) is weak for testing purposes.

2018-12-19 11:39 UTC, kowallus commented on src/main/java/edu/iis/powp/events/predefine/Triangle.java
> +	public ComplexCommand getTriangleDrawCommand(int x, int y, int x1, int y1, int x2, int y2)
y2 parameter is not used

2018-12-19 11:39 UTC, kowallus commented on src/main/java/command/CommandDrawLine.java
> +	private int x, y;
remove getters and setters (used only internally)

2018-12-19 11:39 UTC, kowallus commented on src/main/java/command/CommandSet.java
> +	public int getX() {
remove getters and setters (used only internally)

2019-01-02 10:37 UTC, kowallus commented
Dziękuję. OK.

2019-01-02 10:37 UTC, closed without merging